apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-management-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-management-api
  template:
    metadata:
      labels:
        app: customer-management-api
    spec:
      containers:
      - name: customer-management-api
        image: achdutbar/customer-management-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/shop"
        - name: KAFKA_BROKER
          value: "kafka:9092"
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3