apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-management-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-management-api
  template:
    metadata:
      labels:
        app: customer-management-api
    spec:
      containers:
      - name: customer-management-api
        image: achdutbar/customer-management-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb://mongodb:27017/shop
        - name: KAFKA_BROKER
          value: kafka:9092