apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-ui
  template:
    metadata:
      labels:
        app: customer-ui
    spec:
      containers:
      - name: customer-ui
        image: achdutbar/customer-ui:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "700m"
            memory: "700Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10